### PR TITLE
first try at a stage0 ldscript helper script

### PR DESCRIPTION
**Pull request by hosaka-corp**
Python script that takes a DOL and attempts to statically resolve all the parameters necessary for linking a stage0 payload. 

Might want to test it on a bunch of executables first. Could be touched up with extra patterns too.

**EDIT:** _Here are some notes:_

- This appears to succeed on all versions of the System Menu, but it's still possible that extra patterns might be necessary for other titles; largely depends on the possible existence of some motion in library code over time and/or title-specific linking details
- `payload_addr` not generalizable over all/most instances of input to this program

### CODE REVIEW

**Comment by Leseratte10** [comment]
As already noted on the Discord, this fails when the lower 16 bits of an address are >=0x8000 because this script just uses a binary OR to combine the two values.

**Comment by Leseratte10** [comment]
That new version works properly with PAL MKWii.

**Comment by hosaka-corp** [comment]
Changed the default behavior to render to a template. Apart from the absence of actual testing, this should probably be sufficient for now. Extra patterns can be added later if anyone happens to find any exceptional cases.

**Comment by hosaka-corp** [comment]
Added all 4.3 linkerscripts. We've confirmed that these all work!

**Pull request merged**
